### ISSUE TITLE
Strange behavior when performing operations of single elements with vectors

### ISSUE THREAD

**Issue by marcoalicera** [edzer/units#34] opened 2017-02-15 13:43 UTC
Hi,
I  am using this package and I am performing a simple operation and I am getting what I think is a wrong result. Doing:

```
library(units)
H<-with(ud_units, ((1:10)*0.05)*m)
Q<-with(ud_units,1*m^3/s)
```
I am getting

```
Q
##1 m^3/s
H
##Units: m
## [1] 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50
H*Q
##Units: m^5/s
## [1] 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50

```
On the other hand, with simple values the behavior is as expected

```
H<-with(ud_units, 0.5*m)
Q<-with(ud_units,1*m^3/s)

```
then 

```
Q
##1 m^3/s
H
##0.5 m
H*Q
##0.5 m^4/s
```

Is it a bug?

For reference, I have posted the same here: http://stackoverflow.com/questions/42248894/weird-behavior-of-package-units-or-misunderstanding

**Comment by edzer** [comment] 2017-02-15 20:08
Thanks! Did you try this with the github version of `units`? Everything looks fine to me...

**Comment by marcoalicera** [comment] 2017-02-15 21:27
I am using the package 0.4-2, the one with RStudio.

Every thing looks fine for you because what I got is what what you expect ("Units: m^5/s") or in yours is "Units: m^4/s"?

`version
`
```
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch    

```
How could I update to the github version? I have no admin right on my computer btw.

**Comment by edzer** [comment] 2017-02-16 07:42
Try:

    install.packages("devtools")
    devtools::install_github("edzer/units")

**Comment by jkroes** [comment] 2017-04-18 03:11
I've confirmed that this still seems to be an issue. Installed latest version from Github:
```
install.packages("devtools")
devtools::install_github("edzer/units")
```
Run the following code:
```
c <- set_units(2.99792E+08, m/s)
h <- set_units(6.62607E-34, J*s) # Planck's constant
temp <- set_units(c(5800, 288), K)
h*c/temp
# Units: J*m/K^2
# [1] 3.424901e-29 6.897371e-28
```
Having a vector of length greater than 2 doesn't change the units displayed above.

**Comment by jkroes** [comment] 2017-04-18 04:17
There's also this:
```
lambda <- set_units(log_seq(0, 3, 100), um)
temp <- set_units(c(5800, 288), K)
length(temp)!=1 & length(lambda!=1)
# Error in Ops.units(lambda, 1) : 
# both operands of the expression should be "units" objects
```
Both operands are "units" objects.

**Comment by jkroes** [comment] 2017-04-18 04:19
There's also this:
```
lambda <- set_units(log_seq(0, 3, 100), um)
temp <- set_units(c(5800, 288), K)
length(temp)!=1 & length(lambda!=1)
# Error in Ops.units(lambda, 1) : 
# both operands of the expression should be "units" objects
```
Both variables within length() are units objects. If this means that "1" should be a units object, then this is just further proof that the package doesn't play nice with base R. The length of a vector should be a dimensionless value, because it's just a count of elements within the vector.

**Comment by edzer** [comment] 2017-04-18 22:16
It seems to happen in products or ratio's when one of the vectors gets recycled.

**Comment by edzer** [comment] 2017-04-18 22:40
Pls check whether this fixes the problem.

**Comment by edzer** [comment] 2017-04-19 07:50
false hope; that one only created new problems.

**Comment by edzer** [comment] 2017-04-19 09:33
This should have fixed it. 

`Ops.units` now makes the vectors of equal length in case of product or division before NextMethod is called.

@mailund : this is really a workaround, I'm not so sure I like it. In the reprex above, i.e. in cases where `e1` and `e2` have unequal length, it turns out that `NextMethod()` returns the attributes (units) of `e1` in case all vectors are of equal size, but of `e2` in case they are not, and we don't have a check for that in place. With this workaround, the second case should not occur.

It feels much simpler to
* compute result units only once, call them `u`
* return `.as.units(NextMethod(), u)`

Anything against that?

**Comment by jkroes** [comment] 2017-04-19 18:30
Perfect, that fixed my original example.

**Comment by mailund** [comment] 2017-04-21 06:51
I'm happy with that solution. I'm not really sure why the attributes assigned to the return value depends on the input in this way, but if this solution works, then I can't see anything wrong with it.

**Comment by edzer** [comment] 2017-04-21 07:08
What I would like to understand is why [here](https://github.com/edzer/units/blob/master/R/arith.R#L58-L59) and [here](https://github.com/edzer/units/blob/master/R/arith.R#L61-L62) we assign different units to `e1` and `e2`. 

I think I now do understand why [this](https://github.com/edzer/units/blob/master/R/arith.R#L77) is needed.

**Comment by mailund** [comment] 2017-04-21 08:48
For the first two cases, those operations just translate both e1 and e2 to the same unit before multiplying or dividing. The operations are not actually doing any arithmetic; just manipulating the symbolic representations of the units. I guess I just implemented it this particular way to consider the arithmetic operations and the symbolic units manipulations separately.

I don't actually know why I test for the length of e1 in the second case. I don't see why that should be a special case right now.

**Comment by edzer** [comment] 2017-04-21 08:56
The first two cases do _not_ assign equal units to `e1` and `e2`: `e1` is modified by the first expression, and input to the second. Since the arithmetic is done by `NextMethod()`, units are ignored and this is not caught. I tried to correct this (by providing a copy of `e1` to both) but this led to new problems.

`NextMethod()` can return attributes of either `e1` or `e2`, depending on which one is longer, I don't like that we let it do so.

My feeling is that we make two mistakes that cancel each other out.

In the second case (which is my code & comment) this was needed to deal with the fact that `NextMethod()` does either return attributes of `e1` or of `e2`, I now realize.

**Comment by mailund** [comment] 2017-04-21 09:42
I think the expressions are assigning the same symbolic expressions to `e1` and `e2`---the values are kept. When `NextMethod()` is called, the symbolic values are ignored, so we just multiply or divide numerically, which is fine. It would be prettier just to do the whole thing in one go, though, I agree with that.

**Comment by edzer** [comment] 2017-04-21 10:49
Please look at the expressions again, and if you don't believe it convince yourself by running them in debug and verifying the units of `e1` and `e2` after these two.

**Comment by mailund** [comment] 2017-04-24 15:37
I will definitely get back to it. Sorry I haven't already. I just had a busy weekend. This week is pretty bad as well but I will try to get to it in the weekend. If I don't manage then it will take a little while. I'm at a seminar all of next week and in New York for a conference after that, but it is officially on my todo list and I will figure out what happens :)

-mailund

On 21 Apr 2017, 12.49 +0200, Edzer Pebesma <notifications@github.com>, wrote:

Please look at the expressions again, and if you don't believe it convince yourself by running them in debug and verifying the units of e1 and e2 after these two.

**Closed** 2017-06-04 16:02 UTC
